services:
  ros2_dev:
    build:
      context: .
      args: 
        ADDITIONAL_PACKAGES: ""
      dockerfile: Dockerfile
    container_name: ros2-dev
    volumes:
      - ./ros2_ws/src:/root/ros2_ws/src
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
    entrypoint: "/usr/bin/tail -f /dev/null"
    tty: true

  microros_agent:
    image: microros/micro-ros-agent:humble
    container_name: microros-agent
    network_mode: host
    privileged: true 
    volumes:
      - /dev:/dev
    environment:
      - ROS_DOMAIN_ID=0
    command: "serial --dev /dev/ttyACM0 -v6"
    tty: true
